title: Onyx Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.onyxfic.cc
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#ef4444"
  systems:
    - name: Website
      description: The main website.
      category: Uncategorized
      link: https://example.com/
    - name: Monitors
      description: The part that checks fanfiction platforms.
      category: Uncategorized
    - name: Notifiers
      description: The part that notifies users of changes.
      category: Uncategorized
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#000000"
  enableLastMod: true
  headerTextColor: white
  logo: /img/logo-square-.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#f59e0b"
  notice: "#0ea5e9"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#22c55e"
  categories:
    - name: Uncategorized
      untitled: true
  description: Keep up-to-date with the status of Onyx and its services.
  enableCustomHTML: true
  useLargeHeaderDesign: true
